// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://degfmczxcifyksxjogop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZ2ZtY3p4Y2lmeWtzeGpvZ29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDA0NjksImV4cCI6MjA2MTI3NjQ2OX0.fmiQKy6kBbcWCEgWu5M6w6TssUdNZ0VnWdeopUwmMpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);